//
//import javax.swing.tree.DefaultMutableTreeNode;
//import javax.swing.tree.DefaultTreeModel;
//
///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
// */
//
///**
// *
// * @author lovse
// */
//public class NewJPanel extends javax.swing.JPanel {
//
//
//    DefaultTreeModel model;
//    /**
//     * Creates new form NewJPanel
//     */
//    public NewJPanel() {
//        initComponents();
//    }
//
//    DefaultMutableTreeNode courses = new DefaultMutableTreeNode("Courses")
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jTree1 = new javax.swing.JTree();
//
//        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
//        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("tool");
//        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("feuwfu");
//        treeNode2.add(treeNode3);
//        treeNode1.add(treeNode2);
//        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ewfwef");
//        treeNode1.add(treeNode2);
//        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("wef");
//        treeNode1.add(treeNode2);
//        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("wef");
//        treeNode1.add(treeNode2);
//        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
//        jScrollPane1.setViewportView(jTree1);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        this.setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(96, 96, 96)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(223, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(19, Short.MAX_VALUE))
//        );
//    }// </editor-fold>//GEN-END:initComponents
//
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTree jTree1;
//    // End of variables declaration//GEN-END:variables
//
//jTree1.
//
//}

