
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author lovse
 */

public class NewJFrame extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */

    DefaultTreeModel model;

    public NewJFrame() {
        initComponents();
        ArrayList<Person> p = getPersons();
        Load(p);
    }

    DefaultMutableTreeNode persons = new DefaultMutableTreeNode("Persons");

    public ArrayList<Person> getPersons() {
        DataManipulation dm = new DataManipulation();
        Names_Excel_Provider provider = new Names_Excel_Provider();
        //        Names_Excel_Provider second_provider = new Names_Excel_Provider();
        Courses_Excel_Provider course_provider = new Courses_Excel_Provider();

        course_provider.run();
        provider.run();
//        Warehouse warehouse = new Warehouse(provider);
//        dm.GeneratePersons(provider);
//        dm.GenerateData(course_provider, provider);
        return dm.DataManipulation(course_provider, provider);
    }

    public void Load(ArrayList<Person> stuff) {

        DefaultMutableTreeNode students = new DefaultMutableTreeNode("Students");
        DefaultMutableTreeNode professors = new DefaultMutableTreeNode("Professors");
        for (Person person : stuff) {
            if (person.getClass() == Professor.class) {
                String node = person.getSecond_name()+ " " + person.getName()+ " "+ person.getThird_name();
                DefaultMutableTreeNode prof = new DefaultMutableTreeNode(node);
                ArrayList<Book> books = person.getBooks();
                for (Book book : books) {
                    prof.add(new DefaultMutableTreeNode(book.getTitle()));
                }
                professors.add(prof);
            } else {String node = person.getSecond_name()+ " " + person.getName()+ " "+ person.getThird_name();
                DefaultMutableTreeNode prof = new DefaultMutableTreeNode(node);
                ArrayList<Book> books = person.getBooks();
                for (Book book : books) {
                    prof.add(new DefaultMutableTreeNode(book.getTitle()));
                }
                students.add(prof);
            }
        }
        persons.add(students);
        persons.add(professors);
        model = (DefaultTreeModel) jTree1.getModel();
        model.setRoot(persons);
        jTree1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
